title: Joonas Ryynänen
baseURL: /
params:
  description: Joonas Ryynänen website
  layout_style: overflow
  palette: blue
  header:
    type: header
    template: header
    title: Joonas Ryynänen
    tagline: Software Professional and MSc Student
    profile_img: /images/edustuskuva.jpg
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog/
        style: link
      - label: Thoughts
        url: thoughts
        style: link
        icon_class: lorem-ipsum
        new_window: false
        no_follow: false
        type: action
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Twitter
        url: 'https://twitter.com/JoonasJJP'
        style: icon
        icon_class: fa-twitter
        new_window: true
      - type: action
        template: action
        label: Instagram
        url: 'https://www.instagram.com/jxnestpg/'
        style: icon
        icon_class: fa-instagram
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/JonesTPG'
        style: icon
        icon_class: fa-github
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/joonasjjp97/'
        style: icon
        icon_class: fa-linkedin
        new_window: true
  footer:
    type: footer
    template: footer
    content: ''
  favicon: /images/edustuskuva.jpg
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
